#!/usr/bin/env python3

import os
import sys

import nltk
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # Ensure proper usage.
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets username")

    # Absolute paths to lists.
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # Get user's tweets, store on a list named tweets. Exit program if it fails.
    tweets = helpers.get_user_timeline(sys.argv[1], 50)
    if tweets == None:
        sys.exit("Could not retrieve tweets.")
    
    # Initiate analyzer.    
    analyzer = Analyzer(positives, negatives)
    
    # Iterave over each tweet, analyze it and print score with matching color.
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0:
            print(colored(score, "green"), colored(tweet, "green"))
        elif score < 0:
            print(colored(score, "red"), colored(tweet, "red"))
        else:
            print(colored(score, "yellow"), colored(tweet, "yellow"))

if __name__ == "__main__":
    main()

